import React, { Suspense } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Loading from './loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode,
  // analytics: React.ReactNode,
  // team: React.ReactNode,
  modal: React.ReactNode,
}) {
  return (
    <html lang="en">
      {/* className={inter.className} */}
      <body >
        {/* <Suspense fallback={<Loading />}> */}
        RootLayout: {props.children}
        {/* {props.analytics}
          {props.team} */}
        {props.modal}
        {/* </Suspense> */}
      </body>
    </html>
  )
}
